name: game_clock
description: A multi-clock application to board games
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shelf: ^0.7.5
  equatable: ^1.0.0
  data_connection_checker: ^0.3.4
  dartz: ^0.8.8

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
